version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: hiragana
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hiragana
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minha_rede

  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hiragana?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 8080
      JWT_SECRET: secretaoqueusamudarnoprod
      JWT_EXPIRATION: 86400000
    networks:
      - minha_rede

volumes:
  mysql_data:
    driver: local

networks:
  minha_rede:
    driver: bridge